server:
  port: 8080
  mode: debug
  slow_threshold: 500

logger:
  level: info
  encoding: json

persistence:
  type: memory # Options: memory, mysql

database: # TiDB
  dsn: "user:pass@tcp(127.0.0.1:4000)/test_db?charset=utf8mb4&parseTime=True&loc=Local"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime_minutes: 5

redis:
  addr: "127.0.0.1:6379"
  password: "" # no password by default
  db: 0        # default DB

rocketmq:
  namesrv_addr: "127.0.0.1:9876" # Replace with your RocketMQ NameServer address
  producer_group: "PID_Microservice_MVP"
  consumer_group: "CID_Microservice_MVP"

health_check:
  latency_threshold: 100 # milliseconds
